name = "TussiWord777"
author = "Marco"
version = "1.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "149f24051d91ac1f86830db4bb0814b5a3664d635da735a390e1943a615d5bca"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
